# Generated by Django 5.2.3 on 2025-07-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation_method', models.CharField(choices=[('Straight-line', 'Straight-line'), ('Double declining balance', 'Double declining balance'), ('Units of production', 'Units of production'), ('Sum of years digits', 'Sum of years digits')], max_length=55)),
                ('description', models.TextField(blank=True)),
                ('warranty_expired_at', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disposal_method', models.CharField(choices=[('Scrapping', [('description', 'Physically destroying the asset and disposing of the remains, often used for damaged or obsolete equipment.')]), ('Selling', [('description', 'Asset is sold to a third party (e.g., auction, internal sale, external buyer).')]), ('Trade-in', [('description', 'Asset is exchanged as part of the payment for a new one, often used for vehicles or IT hardware.')]), ('Donating', [('description', 'Giving the asset to a charity, school, or nonprofit. Often requires documentation for transparency.')]), ('Recycling', [('description', 'Sending the asset (or parts of it) to be recycled according to environmental regulations.')]), ('Return to vendor', [('description', 'Returning the asset to the original seller, typically under warranty, lease, or contract terms.')]), ('Internal reuse', [('description', 'Asset is no longer tracked as “assigned,” but is repurposed within the organization (e.g., moved to training/lab environment).')]), ('Lost/Stolen', [('description', 'Asset is no longer recoverable. Must be logged with appropriate documentation or investigation.')]), ('Burned/Damaged Beyond Repair', [('description', 'Used when assets are destroyed in fire, flood, or other irreversible accidents.')])], max_length=255)),
                ('retired_at', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetstatus'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assettype'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.vendor'),
        ),
    ]
