# Generated by Django 5.2.3 on 2025-07-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assignment_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='assets',
        ),
        migrations.AlterModelTable(
            name='assetfiletype',
            table='asset_file_types',
        ),
        migrations.AlterModelTable(
            name='assetstatus',
            table='asset_statuses',
        ),
        migrations.AlterModelTable(
            name='assettype',
            table='asset_types',
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='asset_assignments',
        ),
        migrations.AlterModelTable(
            name='location',
            table='asset_locations',
        ),
        migrations.AlterModelTable(
            name='retirement',
            table='asset_retirements',
        ),
    ]
